The earliest version of MaryTTS was developed around 2000 by Marc Schröder as a collaborative project of http://www.dfki.de/web[DFKI]'s http://www.dfki.de/lt/[Language Technology Lab] and the http://www.coli.uni-saarland.de/groups/WB/Phonetics/[Institute of Phonetics] at http://www.uni-saarland.de[Saarland University]. +
For many years, it evolved and matured, first as an in-house Text-to-Speech (TTS) component, and subsequently as a fully open-source TTS platform with a growing community. +
Since its origins, MaryTTS has changed significantly, but it remains true to its original goal: +
a _**M**odular **A**rchitecture for **R**esearch in s**Y**ynthesis_
 written in Java.

The history of MaryTTS can be largely broken down into several phases:

== Pre-History

Marc and the other early developers have all moved on to other institutions and projects, so little is known about the earliest days of MaryTTS. +
DFKI wanted to develop its own in-house solution for TTS, and the earliest incarnation of what was to become MaryTTS consisted of a collection of shell scripts piping data to each other. +
When Marc joined DFKI, he realized that to create a sustainable and extensible TTS platform, it needed to be redesigned and implemented in an object-oriented way. +
The decision was made in favor of Java (over C++), since platform portability was an important criterion. +

Originally, as described in the first reference publication, MARY was using http://tcts.fpms.ac.be/synthesis/mbrola.html[MBROLA] as a back-end for diphone synthesis of German. +
Support for English was added by integrating code from http://freetts.sourceforge.net/[FreeTTS], a Java port of http://cmuflite.org/[Flite], which was in turn a light-weight runtime implementation of the venerable http://www.cstr.ed.ac.uk/projects/festival/[Festival]. +
In a software project in 2005, students from Saarland University used MARY to create a TTS system for Tibetan.

== MARY 3 (2006-2008)

When MARY development moved the source code from http://www.nongnu.org/cvs/[CVS] to http://subversion.apache.org/[Subversion], the project was already using http://ant.apache.org/[Apache Ant] to manage its build. +
Around the same time, the DFKI-internal MARY code was forked into an open-source project, _OpenMARY_, and managed using a http://trac.edgewall.org/[Trac] instance at http://mary.opendfki.de/[http://mary.opendfki.de/].

Development on MARY was boosted by funding from the http://dfg.de/[German Research Council (DFG)] for a three-year project, "PAVOQUE". +
This provided the resources needed to implement an open-source unit-selection engine, which offers much higher naturalness in the synthesis output, as well as tools to create new TTS voices and even support for new languages.

== OpenMARY (2009-2011)

The internal DFKI MARY was effectively discontinued as development efforts focused on OpenMARY. +
Additional funding was granted by the EU project http://www.semaine-project.eu/[SEMAINE], which integrated MARY into a multimodal, spoken dialog system with expressive virtual characters. +
Along with the final year of the PAVOQUE project and collaboration in another EU project (http://sspnet.eu/[SSPNET]), this phase marked extensive development on MaryTTS. +
In 2011, the development was migrated to GitHub, and http://maven.apache.org/[Apache Maven] replaced Ant as the build management tool.

== MaryTTS (2012-present)

A number of departures resulted in the DFKI Speech Group led by Marc Schröder closing down, with the new Multimodal Speech Processing group led by Ingmar Steiner taking over the MaryTTS project. +
Development on MaryTTS is currently primarily funded through research grants from the DFG, in particular the http://m2ci.org/[Cluster of Excellence _Multimodal Computing and Interaction_ (MMCI)] and the http://www.sfb1102.uni-saarland.de/[Collaborative Research Center SFB-1102].