= MARY TTS 4.3.0: Release notes

link:${project.url}/download/4.3.0/openmary-standalone-install-4.3.0.jar[Download MARY TTS 4.3.0]

This is a feature release, adding new features while maintaining compatibility with existing 4.x voices.

This release marks the final results of work on MARY TTS in the link:../pavoque/[PAVOQUE project], in which we experimented with different technologies for adding expressivity to unit selection synthesis.
The release makes available those project results that may be of interest to a wider audience.

== New features for expressive unit selection synthesis

* selecting style from a multi-style database using a symbolic style feature;
* imposing target prosody using FD-PSOLA signal modification.

Style can be selected using RAWMARYXML's `&lt;prosody style=&quot;...&quot;&gt;` markup (see new expressive voice, below).

Prosody modification is available for all unit selection voices, including older ones;
to activate it, click the checkbox "Apply prosody modification" in the link:${project.url}:59125/[web interface].
This feature should be considered experimental, and the quality depends on many factors, including the accuracy of the pitchmarks used for building the unit selection voice.
While this feature is likely to lead to reduced quality, it enables research on expressive prosody with unit selection voices.

For more information on the MaryXML `&lt;prosody&gt;` markup which can now be applied to all types of MARY voices, see http://mary.opendfki.de/wiki/ProsodySpecificationSupport[ProsodySpecificationSupport].

== New expressive voice

* we release the multi-style expressive German voice 'dfki-pavoque-styles' (660 MB) built from the full PAVOQUE corpus;
 see http://www.dfki.de/web/research/publications?pubid=4877[Steiner et al. (2010)] for a description of this corpus.
 The different styles can be requested using RAWMARYXML `&lt;prosody style=&quot;A_STYLE&quot;&gt;...&lt;/prosody&gt;`, where `A_STYLE` is one of `happy`, `angry`, `sad`, and `poker`.

== New language: Russian

* Nickolay Shmyrev has kindly made available language support for Russian, as well as the Russian male unit selection voice voxforge-ru-nsh.
Thanks Nickolay!

== Bugfixes

* This release also includes a number of bugfixes, see http://mary.opendfki.de/query?status=closed&amp;group=resolution&amp;milestone=4.3[http://mary.opendfki.de/query?status=closed&amp;group=resolution&amp;milestone=4.3]