= Overview
:jbake-type: page
:jbake-status: published
:jbake-cached: true

== Source Code Management

This project uses https://git-scm.com/[Git] to manage its source code. Instructions on Git use can be found at http://git-scm.com/documentation.

== Web Browser Access

The following is a link to a browsable version of the source repository:

`https://github.com/marytts/marytts`

== Anonymous Access

The source can be checked out anonymously from Git with this command (See http://git-scm.com/docs/git-clone):
....
git clone https://github.com/marytts/marytts.git
....

== Developer Access

Only project developers can access the Git tree via this method (See http://git-scm.com/docs/git-clone).
....
git clone git@github.com/marytts/marytts.git
....

== Access from Behind a Firewall

Refer to the documentation of the SCM used for more information about access behind a firewall.

== Issue Management

Issues, bugs, and feature requests should be submitted to the following issue management system for this project.
`https://github.com/marytts/marytts/issues/`

== Project License

Typically the licenses listed for the project are that of the project itself, and not of dependencies.

=== *https://www.gnu.org/licenses/lgpl-3.0-standalone.html[GNU Lesser General Public License v3.0]*